config/routes.rb
Rails.application.routes.draw do
  devise_for :users, sign_out_via: [:get, :post]
  
  root "users#index"


  resources :users do
    resources :posts
  end

  resources :posts do
    resources :comments
    resources :likes
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  validates :text, presence: true

  after_save :update_comments_counter

  private

  def update_comments_counter
    post.update(comments_counter: post.comments.count)
  end
end

app/models/comments.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  validates :text, presence: true

  after_save :update_comments_counter

  private

  def update_comments_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_save :update_likes_counter

  private

  def update_likes_counter
    post.update(likes_counter: post.likes.count)
  end
end

app/models/likes.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_save :update_likes_counter

  private

  def update_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments
  has_many :likes

  after_save :update_posts_counter

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def five_latest_comments
    comments.order('created_at DESC').limit(5)
  end

  def comments_counter
    comments.count
  end

  def likes_counter
    likes.count
  end

  private

  def update_posts_counter
    author.update(posts_counter: author.posts.count)
  end
end

app/models/posts.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :likes
  has_many :comments

  after_save :update_posts_counter

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def five_latest_comments
    comments.order('created_at DESC').limit(5)
  end

  def update_posts_counter
    author.increment!(:posts_counter)
  end

  def five_recent_comments
    comments.order('created_at DESC').limit(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def posts_counter
    posts.count
  end

  def three_latest_posts
    posts.where(author: self).order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :photo, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :photo, :password, :current_password)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    new_comment = current_user.comments.new(post_id: @post.id,
                                            author_id: current_user.id, text: comment_text)
    respond_to do |format|
      format.html do
        if new_comment.save
          redirect_to "/users/#{@post.author_id}/posts/#{@post.id}", notice: 'Success Comment Saved!'
        else
          render :new, status: 'Error occured with Comment!'
        end
      end
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    comment = Comment.find(params[:id])
    comment.destroy
    comment.save
    redirect_to "/users/#{@post.author_id}/posts/#{@post.id}", notice: 'Comment deleted'
  end

  private

  def comment_text
    params.require(:comments).permit(:text)[:text]
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    new_like = current_user.likes.new(author_id: current_user.id, post_id: @post.id)
    if new_like.save
      redirect_to "/users/#{@post.author_id}/posts/#{@post.id}", notice: 'Like Saved!'
    else
      redirect_to "/users/#{@post.author_id}/posts/#{@post.id}", notice: 'Like Error'
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = Post.includes(comments: [:author]).where(posts: { author_id: @user.id })
  end

  def show
    @user = User.find(params[:user_id])
    @post = Post.includes(comments: [:author]).where(posts: { id: params[:id] })[0]
  end

  def new
    @post = Post.new
  end

  def create
    new_post = current_user.posts.new(post_data)
    new_post.likes_counter = 0
    new_post.comments_counter = 0
    respond_to do |format|
      format.html do
        if new_post.save
          redirect_to "/users/#{new_post.author_id}/posts/", notice: 'Success Post Saved!'
        else
          render :new, status: 'Error occured with Post!'
        end
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.author.decrement!(:posts_counter)
    @post.destroy
  end

  private

  def post_data
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevJournal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
  <p class="notice" ><%= notice%> </p>
    <p class="alert"><%= alert%> </p>
    <%= yield %>
  </body>
</html>

app/views/posts/_create_comments.html.erb
<%= form_with url: "/posts/#{@post.id}/comments", scope: :comments do |f| %>
	<%= f.text_area :text, placeholder: "Write something here...", rows: 5, required: true %>
	<%= f.submit "Comment" %>
<% end %>

app/views/posts/index.html.erb
<h1>All posts</h1>
<img src="<%= @user.photo %>" alt="profile_pic">
<%=@user.name %>
<span>number of posts:  <%= @user.posts_counter%> </span>

<% @posts.each do |post| %>

<p><%= link_to post.title, user_post_path(@user,post)%></p>
<p><%= post.text%></p>
<p>comment:<%=post.comments_counter %></p>
<p>likes:<%=post.likes_counter%></p>
<h3> comments </h3>
 <%post.comments.each do |comment|%>
 <p><%=comment.author.name %>: <%=comment.text %></p>
 <%end%>
<%end%>

app/views/posts/new.html.erb
<section>
  <h1>Create a Post</h1>
  <%= form_with model: @post ,url: user_posts_path do |f| %>
    <%= f.label :title, "Title" %>
    <%= f.text_field :title, placeholder: "Title", required: true%>
    <%= f.text_area :text, placeholder: "Write here..", rows: 14, required: true %>
    <%= f.submit "Post" %>
  <% end %>
</section>

app/views/posts/show.html.erb
<main>
    <div><h2 class="post-title"><%= @post.title%> by <%=@post.author.name%> </h2>
    <div><span>comments:<%=@post.comments_counter %></span>
    <span>likes:<%=@post.likes_counter%></span> </div> </div>
<p class="post-text"><%= @post.text %></p>
</div>
 <%= render partial: "create_comments",  local: { post: @post } %>
            <%= form_with url: "/posts/#{@post.id}/likes", scope: :like do |f| %>
        <%= f.submit "Like this post" %>
      <% end %>
<div>
    <h2>comments</h2>
<% @post.five_latest_comments.each do |comment|%>
<p><%= comment.author.name %>:<%= comment.text%> </p>
<% end%>
</main>

app/views/users/index.html.erb
<h1>All users</h1>
<main class="users-container">
<ul class="users">
  <% @users.each do |user| %>
  <div class="user">
    <div class="profile-pics">
   <img class="img" src="<%= user.photo %>" alt="profile_pic">
   </div>
   <div class="profile-info">
    <li class="username">
       <%= link_to user.name, user_path(user)%>
      <p class="post-count">Number of posts: <%= user.posts_counter || 0 %></p>
    </li>
    </div>
    </div>
  <% end %>
</ul>
<%= button_to "sign out", destroy_user_session_path, class: "destroy"%>
</main>

app/views/users/show.html.erb
<h1>Selected User</h1>
<img src="<%= @user.photo %>" alt="profile_pic">
<%= @user.name%>
<%= @user.posts_counter%>
<%= @user.bio%>
<% @user.posts.each do |d|%>
<p><%= link_to d.title, user_post_path(@user,d)%></p>
    <p> <%= d.text %></p>
<%end%>
  <div>
    <%= link_to "Add New Post", "/users/#{@user.id}/posts/new" %>
  </div>
<%= link_to "See all posts", user_posts_path(@user)%>